name: fatigue_env
channels:
  - defaults
dependencies:
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.12.2=haa95532_0
  - expat=2.7.3=h9214b88_0
  - libffi=3.4.4=hd77b12b_1
  - libzlib=1.3.1=h02ab6af_0
  - openssl=3.0.18=h543e019_0
  - pip=25.3=pyhc872135_0
  - python=3.11.14=h981015d_0
  - setuptools=80.9.0=py311haa95532_0
  - sqlite=3.51.0=hda9a48d_0
  - tk=8.6.15=hf199647_0
  - tzdata=2025b=h04d1e81_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.45.1=py311haa95532_0
  - xz=5.6.4=h4754444_1
  - zlib=1.3.1=h02ab6af_0
  - pip:
      - blinker==1.9.0
      - click==8.3.1
      - colorama==0.4.6
      - dlib==20.0.0
      - filelock==3.19.1
      - flask==3.1.2
      - fsspec==2025.9.0
      - imutils==0.5.4
      - itsdangerous==2.2.0
      - jinja2==3.1.6
      - markupsafe==2.1.5
      - mpmath==1.3.0
      - networkx==3.5
      - numpy==2.2.6
      - opencv-python==4.12.0.88
      - pillow==11.3.0
      - scipy==1.16.3
      - sympy==1.14.0
      - torch==2.7.1+cu118
      - torchaudio==2.7.1+cu118
      - torchvision==0.22.1+cu118
      - tqdm==4.67.1
      - typing-extensions==4.15.0
      - werkzeug==3.1.4
prefix: C:\Users\ahmed\miniconda3\envs\fatigue_env
